Productos/Models/ErrorViewModel.cs
using System;

namespace Productos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Productos/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Productos.Models
{
    public class Producto
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public double Precio { get; set; }
        public DateTime FechaCaducidad { get; set; }
        public string Imagen { get; set; }

    }
}

Productos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Productos.Models;

namespace Productos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Productos/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Productos.Models;

namespace Productos.Controllers
{
    public class ProductosController : Controller
    {
        public List<Producto> Productos { get; set; }
        public ProductosController()
        {
            Productos = new List<Producto>
            {
            new Producto { Id = 1, Nombre = "Manzana", Descripcion = "Fruta proveniente del manzano", Tipo = "Fruta", Precio = 0.65, FechaCaducidad = Convert.ToDateTime("16/11/2019"), Imagen = "http://www.redagricola.com/cl/assets/uploads/2017/08/manazana-792x591-c-default.jpg" },
            new Producto { Id = 2, Nombre = "Pera", Descripcion = "Fruta proveniente del peral", Tipo = "Fruta", Precio = 0.75, FechaCaducidad = Convert.ToDateTime("15/11/2019"), Imagen = "https://cde.peru.com//ima/0/1/2/0/6/1206557/611x458/frutas.jpg" },
            new Producto { Id = 3, Nombre = "Ciruela", Descripcion = "Fruta proveniente del ciruelo", Tipo = "Fruta", Precio = 0.55, FechaCaducidad = Convert.ToDateTime("14/11/2019"), Imagen = "https://www.sportlifeargentina.com/media/cache/big/upload/images/article/5c57b1450ee6942e4d34a2f8/5c57b3bb0de694906e3494db-fruta-de-verano-ciruela-para-deportistas.jpg" },
            new Producto { Id = 4, Nombre = "Naranja", Descripcion = "Fruta proveniente del naranjo", Tipo = "Fruta", Precio = 0.29, FechaCaducidad = Convert.ToDateTime("17/11/2019"), Imagen = "https://static.elcorreo.com/www/multimedia/201902/08/media/cortadas/GF0N1J31-U401131236871ktC-U70573831277euB-624x385@El%20Correo-ElCorreo.jpg" },
            new Producto { Id = 5, Nombre = "Melocoton", Descripcion = "Fruta proveniente del melocotonero", Tipo = "Fruta", Precio = 1.3, FechaCaducidad = Convert.ToDateTime("13/11/2019"), Imagen = "https://www.hogarmania.com/archivos/201305/melocotones-xl-668x400x80xX.jpg" }


            
           // return View(empleado.OrderBy(empleado => empleado.Apellido.ToList()));

             };
        }



        public IActionResult Index(string nombre)
        {

            //ViewData["productos"] = Productos.OrderBy(producto => producto.Nombre).ToList();
            //ViewBag.Nombre = "Arrate";

            if (String.IsNullOrEmpty(nombre))
            {
                return View(Productos);
            }

            Productos = Productos.Where(x => x.Nombre.ToLower().Contains(nombre.ToLower())).ToList();
            return View(Productos);

            //return View(Productos.OrderBy(producto => producto.Nombre).ToList());
            
        }

        
        public IActionResult ProductosPrecio()
          {
        
                return View(Productos.OrderBy(producto => producto.Precio).ToList());

            
           
        }

        public IActionResult ProductosTipo()
        {
           
            {

                return View(Productos.OrderBy(producto => producto.Tipo).ToList());

            }
        }
    }
}

Productos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Productos/Views/Productos/Index.cshtml
@model List<Producto>


@{
    ViewData["Title"] = "Index";

    //List <Producto> productos = ViewData["productos"] as List <Producto>;
    //List<Producto> productos = (List <Producto>)ViewData["productos"];
    //string saludo = (string)ViewData["saludo"];
    string nombre = ViewBag.Nombre as string;

}

<form asp-controller="Productos" asp-action="Index">
    <input type="text" placeholder="Nombre" name="nombre" />
    <input type="submit" value="Buscar" />
</form>

<h1>Frutas del Mundo</h1>

<div class="row">
    @*@foreach (Producto Producto in productos)*@
    @foreach (Producto Producto in Model)
    {
        <div class="card col-12 col-sm-6 col-lg-4" style="width: 18rem; ">
            <img src="@Producto.Imagen" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">@Producto.Nombre</h5>
                <p class="card-text">@Producto.Descripcion</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">@Producto.Tipo</li>
                <li class="list-group-item">@Producto.Precio</li>
                <li class="list-group-item">@Producto.FechaCaducidad</li>

            </ul>

        </div>

    }
</div>

Productos/Views/Productos/ProductosPrecio.cshtml
@model List<Producto>
@{
    ViewData["Title"] = "ProductosPrecio";
}

<h1>Precio Frutas</h1>

<div class="row">
    @foreach (Producto Producto in Model)
    {
        <div class="card col-12 col-sm-6 col-lg-4"  style="width: 18rem;">
            <img src="@Producto.Imagen" class="card-img-top" alt="...">
            <div class="card-body ">
                <h5 class="card-title">@Producto.Nombre</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">@Producto.Precio</li>
            </ul>
        </div>
    }
</div>

Productos/Views/Productos/ProductosTipo.cshtml
@model List<Producto>
@{
    ViewData["Title"] = "ProductosTipo";
}

    <h1>Tipo Frutas</h1>

    <div class="row">
        @foreach (Producto Producto in Model)
        {
            <div class="card col-12 col-sm-6 col-lg-4" style=" width: 18rem;">
                <img src="@Producto.Imagen" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@Producto.Nombre</h5>
                    <p class="card-text">@Producto.Descripcion</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@Producto.Tipo</li>

                </ul>

            </div>

        }
    </div>

Productos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Productos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Productos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse ">
                    <ul class="navbar-nav flex-grow-1 ">

                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Productos" asp-action="Home">Index</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle alert-danger" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Productos" asp-action="Index" >Index</a>
                                <a class="dropdown-item" asp-controller="Productos" asp-action="ProductosTipo" >Productos(Tipo)</a>
                                <a class="dropdown-item" asp-controller="Productos" asp-action="ProductosPrecio">Productos(Precio)</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Productos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>